/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrames;

/**
 *
 * @author markez
 */
public class MenuEditar extends javax.swing.JFrame {

    /**
     * Creates new form MenuEditar
     */
    public MenuEditar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblNombreME = new javax.swing.JLabel();
        TxtFieldNombreME = new javax.swing.JTextField();
        CheckBoxActivoME = new javax.swing.JCheckBox();
        LblFechaME = new javax.swing.JLabel();
        LblIdEntranteME = new javax.swing.JLabel();
        LblIdPrimeroME = new javax.swing.JLabel();
        LblIdCombinadoME = new javax.swing.JLabel();
        TxtFieldIdCombinadoME = new javax.swing.JTextField();
        TxtFieldIdPrimeroME = new javax.swing.JTextField();
        TxtFieldIdEntranteME = new javax.swing.JTextField();
        LblIdSegundoME = new javax.swing.JLabel();
        TxtFieldIdSegundoME = new javax.swing.JTextField();
        LblIdPostreME = new javax.swing.JLabel();
        TxtFieldIdPostreME = new javax.swing.JTextField();
        BtnActualizarMenuME = new javax.swing.JButton();
        BtnAtrasME = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblNombreME.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LblNombreME.setText("Nombre:");

        TxtFieldNombreME.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        TxtFieldNombreME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldNombreMEActionPerformed(evt);
            }
        });

        CheckBoxActivoME.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        CheckBoxActivoME.setText("Activo");

        LblFechaME.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LblFechaME.setText("Fecha de creacion:");

        LblIdEntranteME.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LblIdEntranteME.setText("Id del entrante:");

        LblIdPrimeroME.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LblIdPrimeroME.setText("Id del primero:");

        LblIdCombinadoME.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LblIdCombinadoME.setText("Id del primero:");

        TxtFieldIdCombinadoME.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        TxtFieldIdCombinadoME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldIdCombinadoMEActionPerformed(evt);
            }
        });

        TxtFieldIdPrimeroME.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        TxtFieldIdPrimeroME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldIdPrimeroMEActionPerformed(evt);
            }
        });

        TxtFieldIdEntranteME.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        TxtFieldIdEntranteME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldIdEntranteMEActionPerformed(evt);
            }
        });

        LblIdSegundoME.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LblIdSegundoME.setText("Id del segundo:");

        TxtFieldIdSegundoME.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        TxtFieldIdSegundoME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldIdSegundoMEActionPerformed(evt);
            }
        });

        LblIdPostreME.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LblIdPostreME.setText("Id del postre:");

        TxtFieldIdPostreME.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        TxtFieldIdPostreME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldIdPostreMEActionPerformed(evt);
            }
        });

        BtnActualizarMenuME.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnActualizarMenuME.setText("Actualizar menú");
        BtnActualizarMenuME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActualizarMenuMEActionPerformed(evt);
            }
        });

        BtnAtrasME.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnAtrasME.setText("Atrás");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LblIdCombinadoME)
                    .addComponent(LblIdPrimeroME))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtFieldIdPrimeroME, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtFieldIdCombinadoME, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(435, 435, 435))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LblFechaME)
                            .addComponent(LblNombreME)
                            .addComponent(LblIdEntranteME))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtFieldIdEntranteME, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(182, 182, 182)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LblIdPostreME)
                                    .addComponent(LblIdSegundoME))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtFieldIdSegundoME, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtFieldIdPostreME, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(CheckBoxActivoME, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65))
                            .addComponent(TxtFieldNombreME, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnAtrasME, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnActualizarMenuME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblNombreME)
                    .addComponent(TxtFieldNombreME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LblFechaME)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TxtFieldIdEntranteME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LblIdEntranteME))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LblIdSegundoME)
                                .addComponent(TxtFieldIdSegundoME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblIdPostreME)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LblIdPrimeroME)
                                .addComponent(TxtFieldIdPrimeroME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TxtFieldIdPostreME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblIdCombinadoME)
                            .addComponent(TxtFieldIdCombinadoME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(CheckBoxActivoME, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnActualizarMenuME, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAtrasME, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtFieldNombreMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldNombreMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldNombreMEActionPerformed

    private void TxtFieldIdCombinadoMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldIdCombinadoMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldIdCombinadoMEActionPerformed

    private void TxtFieldIdPrimeroMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldIdPrimeroMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldIdPrimeroMEActionPerformed

    private void TxtFieldIdEntranteMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldIdEntranteMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldIdEntranteMEActionPerformed

    private void TxtFieldIdSegundoMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldIdSegundoMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldIdSegundoMEActionPerformed

    private void TxtFieldIdPostreMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldIdPostreMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldIdPostreMEActionPerformed

    private void BtnActualizarMenuMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActualizarMenuMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnActualizarMenuMEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuEditar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizarMenuME;
    private javax.swing.JButton BtnAtrasME;
    private javax.swing.JCheckBox CheckBoxActivoME;
    private javax.swing.JLabel LblFechaME;
    private javax.swing.JLabel LblIdCombinadoME;
    private javax.swing.JLabel LblIdEntranteME;
    private javax.swing.JLabel LblIdPostreME;
    private javax.swing.JLabel LblIdPrimeroME;
    private javax.swing.JLabel LblIdSegundoME;
    private javax.swing.JLabel LblNombreME;
    private javax.swing.JTextField TxtFieldIdCombinadoME;
    private javax.swing.JTextField TxtFieldIdEntranteME;
    private javax.swing.JTextField TxtFieldIdPostreME;
    private javax.swing.JTextField TxtFieldIdPrimeroME;
    private javax.swing.JTextField TxtFieldIdSegundoME;
    private javax.swing.JTextField TxtFieldNombreME;
    // End of variables declaration//GEN-END:variables
}
