package JFrames;


public class MenuNuevo extends javax.swing.JFrame {

    /**
     * Creates new form MenuNuevo
     */
    public MenuNuevo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblNombreMN = new javax.swing.JLabel();
        TxtFieldNombreMN = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        LblFechaMN = new javax.swing.JLabel();
        LblIdPrimeroMN = new javax.swing.JLabel();
        TxtFieldIdEntranteMN = new javax.swing.JTextField();
        LblIdSegundoMN = new javax.swing.JLabel();
        TxtFieldIdPrimeroMN = new javax.swing.JTextField();
        LblIdEntranteMN = new javax.swing.JLabel();
        TxtFieldIdSegundoMN = new javax.swing.JTextField();
        LblIdPostreMN = new javax.swing.JLabel();
        TxtFieldIdPostreMN = new javax.swing.JTextField();
        LblIdCombinadoMN = new javax.swing.JLabel();
        TxtFieldIdCombinadoMN = new javax.swing.JTextField();
        BtnAtrasMN = new javax.swing.JButton();
        BtnCrearMenuMN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblNombreMN.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LblNombreMN.setText("Nombre:");

        TxtFieldNombreMN.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        TxtFieldNombreMN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldNombreMNActionPerformed(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jCheckBox1.setText("Activo");

        LblFechaMN.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LblFechaMN.setText("Fecha de creacion:");

        LblIdPrimeroMN.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LblIdPrimeroMN.setText("Id del primero:");

        TxtFieldIdEntranteMN.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        TxtFieldIdEntranteMN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldIdEntranteMNActionPerformed(evt);
            }
        });

        LblIdSegundoMN.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LblIdSegundoMN.setText("Id del segundo:");

        TxtFieldIdPrimeroMN.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        TxtFieldIdPrimeroMN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldIdPrimeroMNActionPerformed(evt);
            }
        });

        LblIdEntranteMN.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LblIdEntranteMN.setText("Id del entrante:");

        TxtFieldIdSegundoMN.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        TxtFieldIdSegundoMN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldIdSegundoMNActionPerformed(evt);
            }
        });

        LblIdPostreMN.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LblIdPostreMN.setText("Id del postre:");

        TxtFieldIdPostreMN.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        TxtFieldIdPostreMN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldIdPostreMNActionPerformed(evt);
            }
        });

        LblIdCombinadoMN.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LblIdCombinadoMN.setText("Id del plato combinado:");

        TxtFieldIdCombinadoMN.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        TxtFieldIdCombinadoMN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldIdCombinadoMNActionPerformed(evt);
            }
        });

        BtnAtrasMN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnAtrasMN.setText("Atrás");
        BtnAtrasMN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtrasMNActionPerformed(evt);
            }
        });

        BtnCrearMenuMN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtnCrearMenuMN.setText("Crear nuevo menu");
        BtnCrearMenuMN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearMenuMNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LblIdCombinadoMN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtFieldIdCombinadoMN, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblIdPrimeroMN, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LblIdEntranteMN, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtFieldIdPrimeroMN, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtFieldIdEntranteMN, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(393, 393, 393))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LblFechaMN)
                            .addComponent(LblNombreMN))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(280, 280, 280)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LblIdPostreMN)
                                        .addGap(18, 18, 18)
                                        .addComponent(TxtFieldIdPostreMN, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LblIdSegundoMN))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtFieldIdSegundoMN, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TxtFieldNombreMN, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(205, 205, 205))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnAtrasMN, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149)
                        .addComponent(BtnCrearMenuMN, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblNombreMN)
                    .addComponent(TxtFieldNombreMN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblFechaMN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtFieldIdEntranteMN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LblIdSegundoMN)
                        .addComponent(TxtFieldIdSegundoMN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LblIdEntranteMN)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblIdPrimeroMN)
                    .addComponent(TxtFieldIdPrimeroMN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblIdPostreMN)
                    .addComponent(TxtFieldIdPostreMN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblIdCombinadoMN)
                    .addComponent(TxtFieldIdCombinadoMN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAtrasMN, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCrearMenuMN, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtFieldNombreMNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldNombreMNActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldNombreMNActionPerformed

    private void TxtFieldIdEntranteMNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldIdEntranteMNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldIdEntranteMNActionPerformed

    private void TxtFieldIdPrimeroMNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldIdPrimeroMNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldIdPrimeroMNActionPerformed

    private void TxtFieldIdSegundoMNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldIdSegundoMNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldIdSegundoMNActionPerformed

    private void TxtFieldIdPostreMNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldIdPostreMNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldIdPostreMNActionPerformed

    private void TxtFieldIdCombinadoMNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldIdCombinadoMNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldIdCombinadoMNActionPerformed

    private void BtnCrearMenuMNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearMenuMNActionPerformed

        //funcion para agregar el menu a la base de datos
        //funcion para comprobar que todo esta correcto
        //funcion para mostrar mensage del resultado
        
        Menus abrir = new Menus();
        abrir.setVisible(true);
        this.setVisible(false);

       
    }//GEN-LAST:event_BtnCrearMenuMNActionPerformed

    private void BtnAtrasMNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtrasMNActionPerformed

        Menus abrir = new Menus();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnAtrasMNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuNuevo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAtrasMN;
    private javax.swing.JButton BtnCrearMenuMN;
    private javax.swing.JLabel LblFechaMN;
    private javax.swing.JLabel LblIdCombinadoMN;
    private javax.swing.JLabel LblIdEntranteMN;
    private javax.swing.JLabel LblIdPostreMN;
    private javax.swing.JLabel LblIdPrimeroMN;
    private javax.swing.JLabel LblIdSegundoMN;
    private javax.swing.JLabel LblNombreMN;
    private javax.swing.JTextField TxtFieldIdCombinadoMN;
    private javax.swing.JTextField TxtFieldIdEntranteMN;
    private javax.swing.JTextField TxtFieldIdPostreMN;
    private javax.swing.JTextField TxtFieldIdPrimeroMN;
    private javax.swing.JTextField TxtFieldIdSegundoMN;
    private javax.swing.JTextField TxtFieldNombreMN;
    private javax.swing.JCheckBox jCheckBox1;
    // End of variables declaration//GEN-END:variables
}
