/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrames;

/**
 *
 * @author markez
 */
public class MenuVer extends javax.swing.JFrame {

    /**
     * Creates new form MenuVer
     */
    public MenuVer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        LblFechaMV = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        LblIdEntranteMV = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        LblIdPrimeroMV = new javax.swing.JLabel();
        LblIdCombinadoMV = new javax.swing.JLabel();
        LblIdSegundoMV = new javax.swing.JLabel();
        LblNombreMV = new javax.swing.JLabel();
        LblIdPostreMV = new javax.swing.JLabel();
        CheckBoxActivoMV = new javax.swing.JCheckBox();
        LblVNombreMV = new javax.swing.JLabel();
        LblVFechaMV = new javax.swing.JLabel();
        LblVIdPrimeroMV = new javax.swing.JLabel();
        LblVIdEntranteMV = new javax.swing.JLabel();
        LblVIdCombinadoMV = new javax.swing.JLabel();
        LblVIdSegundoMV = new javax.swing.JLabel();
        LblVIdPostreMV = new javax.swing.JLabel();

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setText("Nombre:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblFechaMV.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LblFechaMV.setText("Fecha de creacion:");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Actualizar menú");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        LblIdEntranteMV.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LblIdEntranteMV.setText("Id del entrante:");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Atrás");

        LblIdPrimeroMV.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LblIdPrimeroMV.setText("Id del primero:");

        LblIdCombinadoMV.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LblIdCombinadoMV.setText("Id del combinado:");

        LblIdSegundoMV.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LblIdSegundoMV.setText("Id del segundo:");

        LblNombreMV.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LblNombreMV.setText("Nombre:");

        LblIdPostreMV.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LblIdPostreMV.setText("Id del postre:");

        CheckBoxActivoMV.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        CheckBoxActivoMV.setText("Activo");

        LblVNombreMV.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LblVNombreMV.setText("nombre1");

        LblVFechaMV.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LblVFechaMV.setText("23/03/2004");

        LblVIdPrimeroMV.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LblVIdPrimeroMV.setText("2");

        LblVIdEntranteMV.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LblVIdEntranteMV.setText("3");

        LblVIdCombinadoMV.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LblVIdCombinadoMV.setText("4");

        LblVIdSegundoMV.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LblVIdSegundoMV.setText("23");

        LblVIdPostreMV.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LblVIdPostreMV.setText("6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LblIdCombinadoMV, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(LblIdPrimeroMV, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(LblIdEntranteMV, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(LblFechaMV)
                                .addComponent(LblNombreMV))
                            .addGap(1, 1, 1)))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblVFechaMV, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LblVNombreMV, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblVIdCombinadoMV, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LblVIdPrimeroMV, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LblIdPostreMV))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LblVIdEntranteMV, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LblIdSegundoMV)))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblVIdPostreMV, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblVIdSegundoMV, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CheckBoxActivoMV, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblNombreMV)
                    .addComponent(CheckBoxActivoMV, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblVNombreMV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblFechaMV)
                    .addComponent(LblVFechaMV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblIdSegundoMV)
                    .addComponent(LblIdEntranteMV)
                    .addComponent(LblVIdEntranteMV)
                    .addComponent(LblVIdSegundoMV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblIdPrimeroMV)
                    .addComponent(LblIdPostreMV)
                    .addComponent(LblVIdPrimeroMV)
                    .addComponent(LblVIdPostreMV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblIdCombinadoMV)
                    .addComponent(LblVIdCombinadoMV))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuVer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuVer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuVer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuVer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuVer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBoxActivoMV;
    private javax.swing.JLabel LblFechaMV;
    private javax.swing.JLabel LblIdCombinadoMV;
    private javax.swing.JLabel LblIdEntranteMV;
    private javax.swing.JLabel LblIdPostreMV;
    private javax.swing.JLabel LblIdPrimeroMV;
    private javax.swing.JLabel LblIdSegundoMV;
    private javax.swing.JLabel LblNombreMV;
    private javax.swing.JLabel LblVFechaMV;
    private javax.swing.JLabel LblVIdCombinadoMV;
    private javax.swing.JLabel LblVIdEntranteMV;
    private javax.swing.JLabel LblVIdPostreMV;
    private javax.swing.JLabel LblVIdPrimeroMV;
    private javax.swing.JLabel LblVIdSegundoMV;
    private javax.swing.JLabel LblVNombreMV;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
