package JFrames;

import Classes.Receta;
import ConexionesBD.ConexionMYSQLServer;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author markez
 */
public class RecetaEditar extends javax.swing.JFrame {

    String nombre, tipo, ingredientes, preparacion, fecha, ultimaModificacion;
    int id;

    //conexion
    ConexionMYSQLServer cc = new ConexionMYSQLServer();
    Connection con = cc.conectar();
    
    ResultSet rs = null;
    Statement st = null;
    

    public RecetaEditar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblTipoRE = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtAreaPreparacionRE = new javax.swing.JTextArea();
        BtnAtrasRE = new javax.swing.JButton();
        LblPreparacionRE = new javax.swing.JLabel();
        BtnCrearRecetaRE = new javax.swing.JButton();
        LblNombreRE = new javax.swing.JLabel();
        LblFechaRE = new javax.swing.JLabel();
        TxtFieldNombreRE = new javax.swing.JTextField();
        LblIngredientesRE = new javax.swing.JLabel();
        ComboBoxTipoRE = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtAreaIngredientesRE = new javax.swing.JTextArea();
        TxtFieldIdRE = new javax.swing.JTextField();
        LblIdRE = new javax.swing.JLabel();
        LblFechaMostrarRE = new javax.swing.JLabel();
        LblUltimaModificacionRE = new javax.swing.JLabel();
        LblUltimaModificacionMostrarRE = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        LblTipoRE.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        LblTipoRE.setText("Tipo de receta: *");

        TxtAreaPreparacionRE.setColumns(20);
        TxtAreaPreparacionRE.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        TxtAreaPreparacionRE.setLineWrap(true);
        TxtAreaPreparacionRE.setRows(5);
        jScrollPane2.setViewportView(TxtAreaPreparacionRE);

        BtnAtrasRE.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        BtnAtrasRE.setText("Atrás");
        BtnAtrasRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtrasREActionPerformed(evt);
            }
        });

        LblPreparacionRE.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        LblPreparacionRE.setText("Preparación: *");

        BtnCrearRecetaRE.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        BtnCrearRecetaRE.setText("Actualizar receta");
        BtnCrearRecetaRE.setActionCommand("");
        BtnCrearRecetaRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearRecetaREActionPerformed(evt);
            }
        });

        LblNombreRE.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        LblNombreRE.setText("Nombre: *");

        LblFechaRE.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        LblFechaRE.setText("Fecha de creacion:");

        TxtFieldNombreRE.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N

        LblIngredientesRE.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        LblIngredientesRE.setText("Ingredientes: *");

        ComboBoxTipoRE.setEditable(true);
        ComboBoxTipoRE.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        ComboBoxTipoRE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrante", "Primero", "Segundo", "Plato Combinado", "Postre" }));
        ComboBoxTipoRE.setSelectedIndex(-1);

        TxtAreaIngredientesRE.setColumns(20);
        TxtAreaIngredientesRE.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        TxtAreaIngredientesRE.setLineWrap(true);
        TxtAreaIngredientesRE.setRows(5);
        jScrollPane1.setViewportView(TxtAreaIngredientesRE);

        TxtFieldIdRE.setEditable(false);
        TxtFieldIdRE.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N

        LblIdRE.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        LblIdRE.setText("Id: *");

        LblFechaMostrarRE.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        LblFechaMostrarRE.setText("Fecha");

        LblUltimaModificacionRE.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        LblUltimaModificacionRE.setText("Ultima modificación:");

        LblUltimaModificacionMostrarRE.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        LblUltimaModificacionMostrarRE.setText("Fecha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LblPreparacionRE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnAtrasRE, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblIngredientesRE, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LblTipoRE, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LblNombreRE, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LblIdRE, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LblFechaRE, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnCrearRecetaRE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addComponent(TxtFieldNombreRE, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(TxtFieldIdRE, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LblFechaMostrarRE, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LblUltimaModificacionRE)
                                        .addGap(18, 18, 18)
                                        .addComponent(LblUltimaModificacionMostrarRE, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(ComboBoxTipoRE, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(268, 268, 268))))))
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtFieldIdRE)
                    .addComponent(LblIdRE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtFieldNombreRE)
                    .addComponent(LblNombreRE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblTipoRE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboBoxTipoRE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblIngredientesRE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblPreparacionRE, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LblFechaMostrarRE, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LblUltimaModificacionRE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LblUltimaModificacionMostrarRE))
                    .addComponent(LblFechaRE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAtrasRE, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                    .addComponent(BtnCrearRecetaRE, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void BtnCrearRecetaREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearRecetaREActionPerformed

        modificarReceta();

    }//GEN-LAST:event_BtnCrearRecetaREActionPerformed

    private void BtnAtrasREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtrasREActionPerformed
        //cierro ventana actual, abro ventana recetas.
        Recetas abrir = new Recetas();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnAtrasREActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
        rellenarComboTipos();
        
        mostrarValoresAntiguos();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecetaEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecetaEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecetaEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecetaEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecetaEditar().setVisible(true);
            }
        });
    }

    public void mostrarValoresAntiguos() {
        int index = -1;
        
        switch (tipo) {
            case "Entrante":
                index = 0;
                break;
            case "Primero":
                index = 1;
                break;
            case "Segundo":
                index = 2;
                break;
            case "Plato Combinado":
                index = 3;
                break;
            case "Postre":
                index = 4;
                break;
            default:
                index = -1;
                break;
        }

        //mostrar los valores antiguos en las celdas
        TxtFieldIdRE.setText(String.valueOf(id));
        TxtFieldNombreRE.setText(nombre);
        ComboBoxTipoRE.setSelectedIndex(index);
        TxtAreaIngredientesRE.setText(ingredientes);
        TxtAreaPreparacionRE.setText(preparacion);
        LblFechaMostrarRE.setText(fecha);
        LblUltimaModificacionMostrarRE.setText(ultimaModificacion);
    }

    public void modificarReceta() {
        //declaro variables
        String nombreE = "", tipoE = "", ingredientesE = "", preparacionE = "", ultimaModificacionE = "";
        int idE;
        boolean todoOk = false;

        //recogo valores de los campos y los guardo en las variables
        idE = Integer.parseInt(TxtFieldIdRE.getText());
        nombreE = TxtFieldNombreRE.getText();
        tipoE = ComboBoxTipoRE.getItemAt(ComboBoxTipoRE.getSelectedIndex());
        ingredientesE = TxtAreaIngredientesRE.getText();
        preparacionE = TxtAreaPreparacionRE.getText();
        ultimaModificacionE = RecetaNueva.fechaActual();

        //comprovaciones varias de que los valores son correctos
        if (nombreE.equals("")) {
            JOptionPane.showMessageDialog(null, "El nombre no puede estar vacio.");
        } else if (tipoE == null || tipoE.equals("")) {
            JOptionPane.showMessageDialog(null, "Has de seleccionar un tipo de plato.");
        } else if (ingredientesE.equals("")) {
            JOptionPane.showMessageDialog(null, "Has de indicar los ingredientes.");
        } else if (preparacionE.equals("")) {
            JOptionPane.showMessageDialog(null, "Has de indicar la preparacion.");
        } else {
            todoOk = true;
        }

        if (todoOk) {
            //guardar datos en base de datos usando UPDATE
            //la fecha no se toca nunca, (el id creo que tampoco)
            String SQL = "UPDATE recetas SET nombre = '" + nombreE + "', "
                    + "tipo = '" + tipoE + "', ingredientes = '" + ingredientesE + "',"
                    + " preparacion = '"+preparacionE+"', ultima_modificacion = '"+ultimaModificacionE+"' WHERE id = '" + idE + "'";
            cc.actualizarReceta(SQL, con);
            
            //vuelvo a recetas
            Recetas abrir = new Recetas();
            abrir.setVisible(true);
            this.dispose();
        }
        
    }
    
    
    public void rellenarComboTipos() {
        
        String SQL = "Select tipo FROM tipos";
        String tipo;
        
        ComboBoxTipoRE.removeAllItems(); //bacio el comboBox

        try {
            //recojo los valores en un el arraylist
            st = con.createStatement();
            rs = st.executeQuery(SQL);
            
            boolean r = rs.next();
            while (r) {
                tipo = rs.getString("tipo");
                ComboBoxTipoRE.addItem(tipo);
                r = rs.next();
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al cargar TIPOS en ComboBox tipos.");
            
        }
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAtrasRE;
    private javax.swing.JButton BtnCrearRecetaRE;
    private javax.swing.JComboBox<String> ComboBoxTipoRE;
    private javax.swing.JLabel LblFechaMostrarRE;
    private javax.swing.JLabel LblFechaRE;
    private javax.swing.JLabel LblIdRE;
    private javax.swing.JLabel LblIngredientesRE;
    private javax.swing.JLabel LblNombreRE;
    private javax.swing.JLabel LblPreparacionRE;
    private javax.swing.JLabel LblTipoRE;
    private javax.swing.JLabel LblUltimaModificacionMostrarRE;
    private javax.swing.JLabel LblUltimaModificacionRE;
    private javax.swing.JTextArea TxtAreaIngredientesRE;
    private javax.swing.JTextArea TxtAreaPreparacionRE;
    private javax.swing.JTextField TxtFieldIdRE;
    private javax.swing.JTextField TxtFieldNombreRE;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
