package JFrames;

import Classes.Receta;
import ConexionesBD.ConexionMYSQLServer;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author markez
 */
public class RecetaEditar extends javax.swing.JFrame {

    String nombre, tipo, ingredientes, preparacion, fecha, ultimaModificacion;
    int id;

    //conexion
    ConexionMYSQLServer cc = new ConexionMYSQLServer();
    Connection con = cc.conectar();
    
    ResultSet rs = null;
    Statement st = null;
    

    public RecetaEditar() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblTipoRE = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtAreaPreparacionRE = new javax.swing.JTextArea();
        BtnAtrasRE = new javax.swing.JButton();
        LblPreparacionRE = new javax.swing.JLabel();
        BtnCrearRecetaRE = new javax.swing.JButton();
        LblNombreRE = new javax.swing.JLabel();
        LblFechaRE = new javax.swing.JLabel();
        TxtFieldNombreRE = new javax.swing.JTextField();
        LblIngredientesRE = new javax.swing.JLabel();
        ComboBoxTipoRE = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtAreaIngredientesRE = new javax.swing.JTextArea();
        LblIdRE = new javax.swing.JLabel();
        LblFechaMostrarRE = new javax.swing.JLabel();
        LblUltimaModificacionRE = new javax.swing.JLabel();
        LblUltimaModificacionMostrarRE = new javax.swing.JLabel();
        LabelEditIdRE = new javax.swing.JLabel();
        BtnEliminarRecetaRE = new javax.swing.JButton();
        BtnEditarRecetaRE = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ver / Editar Receta:");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        LblTipoRE.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        LblTipoRE.setText("Tipo de receta: *");

        TxtAreaPreparacionRE.setEditable(false);
        TxtAreaPreparacionRE.setColumns(20);
        TxtAreaPreparacionRE.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        TxtAreaPreparacionRE.setLineWrap(true);
        TxtAreaPreparacionRE.setRows(5);
        jScrollPane2.setViewportView(TxtAreaPreparacionRE);

        BtnAtrasRE.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        BtnAtrasRE.setText("Atrás");
        BtnAtrasRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtrasREActionPerformed(evt);
            }
        });

        LblPreparacionRE.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        LblPreparacionRE.setText("Preparación: *");

        BtnCrearRecetaRE.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        BtnCrearRecetaRE.setText("Actualizar receta");
        BtnCrearRecetaRE.setActionCommand("");
        BtnCrearRecetaRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearRecetaREActionPerformed(evt);
            }
        });

        LblNombreRE.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        LblNombreRE.setText("Nombre: *");

        LblFechaRE.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        LblFechaRE.setText("Fecha de creación:");

        TxtFieldNombreRE.setEditable(false);
        TxtFieldNombreRE.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N

        LblIngredientesRE.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        LblIngredientesRE.setText("Ingredientes: *");

        ComboBoxTipoRE.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        ComboBoxTipoRE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrante", "Primero", "Segundo", "Plato Combinado", "Postre" }));
        ComboBoxTipoRE.setSelectedIndex(-1);

        TxtAreaIngredientesRE.setEditable(false);
        TxtAreaIngredientesRE.setColumns(20);
        TxtAreaIngredientesRE.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        TxtAreaIngredientesRE.setLineWrap(true);
        TxtAreaIngredientesRE.setRows(5);
        jScrollPane1.setViewportView(TxtAreaIngredientesRE);

        LblIdRE.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        LblIdRE.setText("Id: *");

        LblFechaMostrarRE.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        LblFechaMostrarRE.setText("Fecha");

        LblUltimaModificacionRE.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        LblUltimaModificacionRE.setText("Ultima modificación:");

        LblUltimaModificacionMostrarRE.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        LblUltimaModificacionMostrarRE.setText("Fecha");

        LabelEditIdRE.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        LabelEditIdRE.setText("3308");

        BtnEliminarRecetaRE.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        BtnEliminarRecetaRE.setText("Eliminar receta");
        BtnEliminarRecetaRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarRecetaREActionPerformed(evt);
            }
        });

        BtnEditarRecetaRE.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        BtnEditarRecetaRE.setText("EditarReceta");
        BtnEditarRecetaRE.setToolTipText("");
        BtnEditarRecetaRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarRecetaREActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LblPreparacionRE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnAtrasRE, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblIngredientesRE, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LblTipoRE, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LblNombreRE, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LblIdRE, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LblFechaRE, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnEliminarRecetaRE, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnCrearRecetaRE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelEditIdRE, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnEditarRecetaRE, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(TxtFieldNombreRE)
                                .addGap(178, 178, 178))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LblFechaMostrarRE, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LblUltimaModificacionRE)
                                        .addGap(18, 18, 18)
                                        .addComponent(LblUltimaModificacionMostrarRE, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(ComboBoxTipoRE, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(268, 268, 268))))))
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblIdRE, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelEditIdRE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnEditarRecetaRE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtFieldNombreRE)
                    .addComponent(LblNombreRE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblTipoRE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboBoxTipoRE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblIngredientesRE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblPreparacionRE, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LblFechaMostrarRE, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LblUltimaModificacionRE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LblUltimaModificacionMostrarRE))
                    .addComponent(LblFechaRE, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAtrasRE, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCrearRecetaRE, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                    .addComponent(BtnEliminarRecetaRE, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void BtnCrearRecetaREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearRecetaREActionPerformed

        modificarReceta();

    }//GEN-LAST:event_BtnCrearRecetaREActionPerformed

    private void BtnAtrasREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtrasREActionPerformed
        //cierro ventana actual, abro ventana recetas.
        Recetas abrir = new Recetas();
        abrir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnAtrasREActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
        cc.rellenarComboTipos(ComboBoxTipoRE, con);
        
        mostrarValoresAntiguos();
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void BtnEliminarRecetaREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarRecetaREActionPerformed

        if (JOptionPane.showConfirmDialog(null, "Seguro que deseas borrar la receta?", "Aviso importante!",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) 
        {
            //yes option
            
           //borrar receta de la bd + mostrar mensaje de que se ha borrado.
            String SQL = "DELETE FROM recetas WHERE id = '" + id + "'";
            cc.borrarReceta(SQL, con);
            
            //una vez borrada, volvemos al JFrame "recetas".
            Recetas abrir = new Recetas();
            abrir.setVisible(true);
            this.dispose();
        } else {
            // no option
        }
    }//GEN-LAST:event_BtnEliminarRecetaREActionPerformed

    private void BtnEditarRecetaREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarRecetaREActionPerformed
        
        TxtFieldNombreRE.setEditable(true);
        TxtAreaIngredientesRE.setEditable(true);
        TxtAreaPreparacionRE.setEditable(true);
        
        JOptionPane.showMessageDialog(null, "Ahora puedes modificar la receta.", "Info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_BtnEditarRecetaREActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecetaEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecetaEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecetaEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecetaEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecetaEditar().setVisible(true);
            }
        });
    }

    public void mostrarValoresAntiguos() {
        int index = -1;
        
        switch (tipo) {
            case "Entrante":
                index = 1;
                break;
            case "Primero":
                index = 2;
                break;
            case "Segundo":
                index = 3;
                break;
            case "Combinado":
                index = 4;
                break;
            case "Postre":
                index = 5;
                break;
            case "Otro":
                index = 6;
            default:
                index = 0;
                break;
        }

        //mostrar los valores antiguos en las celdas
        LabelEditIdRE.setText(String.valueOf(id));
        TxtFieldNombreRE.setText(nombre);
        ComboBoxTipoRE.setSelectedIndex(index);
        TxtAreaIngredientesRE.setText(ingredientes);
        TxtAreaPreparacionRE.setText(preparacion);
        LblFechaMostrarRE.setText(fecha);
        LblUltimaModificacionMostrarRE.setText(ultimaModificacion);
    }

    public void modificarReceta() {
        //declaro variables
        String nombreE = "", tipoE = "", ingredientesE = "", preparacionE = "";
        int idE;
        boolean todoOk = false;

        //recogo valores de los campos y los guardo en las variables
        idE = Integer.parseInt(LabelEditIdRE.getText());
        nombreE = TxtFieldNombreRE.getText().replace("'", "''"); //para que se puedan agregar apostrofes
        tipoE = ComboBoxTipoRE.getItemAt(ComboBoxTipoRE.getSelectedIndex());
        ingredientesE = TxtAreaIngredientesRE.getText().replace("'", "''");;
        preparacionE = TxtAreaPreparacionRE.getText().replace("'", "''");;
        Date ultimaModificacionE = RecetaNueva.fechaActualDate();

        
        //se comprueban las variables
        if (RecetaNueva.comprovarVariables(nombreE, tipoE, ingredientesE, preparacionE)) {
            //guardar datos en base de datos usando UPDATE
            //la fecha no se toca nunca, (el id creo que tampoco)
            String SQL = "UPDATE recetas SET nombre = '" + nombreE + "', "
                    + "tipo = '" + tipoE + "', ingredientes = '" + ingredientesE + "',"
                    + " preparacion = '"+preparacionE+"', ultima_modificacion = '"+ultimaModificacionE+"' WHERE id = '" + idE + "'";
            cc.actualizarReceta(SQL, con);
            
            //vuelvo a recetas
            Recetas abrir = new Recetas();
            abrir.setVisible(true);
            this.dispose();
        }
        
    }
    
    
    
        
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAtrasRE;
    private javax.swing.JButton BtnCrearRecetaRE;
    private javax.swing.JButton BtnEditarRecetaRE;
    private javax.swing.JButton BtnEliminarRecetaRE;
    private javax.swing.JComboBox<String> ComboBoxTipoRE;
    private javax.swing.JLabel LabelEditIdRE;
    private javax.swing.JLabel LblFechaMostrarRE;
    private javax.swing.JLabel LblFechaRE;
    private javax.swing.JLabel LblIdRE;
    private javax.swing.JLabel LblIngredientesRE;
    private javax.swing.JLabel LblNombreRE;
    private javax.swing.JLabel LblPreparacionRE;
    private javax.swing.JLabel LblTipoRE;
    private javax.swing.JLabel LblUltimaModificacionMostrarRE;
    private javax.swing.JLabel LblUltimaModificacionRE;
    private javax.swing.JTextArea TxtAreaIngredientesRE;
    private javax.swing.JTextArea TxtAreaPreparacionRE;
    private javax.swing.JTextField TxtFieldNombreRE;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
